### ISSUE TITLE
Documentation for Crypto is outdated

### ISSUE THREAD

**Issue by GerardSoleCa** [sensedeep/onedoc#8]
**Setup for encrypting values differs from documentation**
We have been trying to integrate value encryption using this project.
We have succeeded, but it was a painful process since the documentation is not updated and differs from real software implementation.

After checking the documentation, the sample projects shared in Github and the source code itself. 
We saw that the encryption supports (partially at my understanding) multi key. So when defining the Table constructor, we can specify there multiple keys, while the "primary" one is the one that will be always used.

The documentation doesn't show that structure. It depicts a flatter structure where no key names are associated.

Then, jumping to the schema definition. 
The documentation says that `encrypt: true` enables encryption. But checking both the samples and source code we found that we need to put `crypto: true` in order to enable encryption.

Finally, I was trying to understand how the code selects the proper encryption key, so we can specify "primary" or any other value. I see references to `name` on the field, but I don't know exactly where/how that `name` field is populated.

**Create a pull request**

To be discussed.

**Comment by mobsense** [comment]
Thanks for the feedback. Appreciated. Let us look into this and get back to you with any questions.

**Comment by mobsense** [comment]
The schema/model doc that says: "encrypt: true" should be "crypt: true" as you say. We'll correct that.

The Table constructor `crypto` property defines the configuration used to encrypt and decrypt attributes that specify `crypt: true` in their schema.

The crypto property should be set to a hash that a "primary" property that contains the `cipher` to use and an encryption secret/password. Currently, only a single encryption key called "primary" is supported.

For example:

```javascript
let db = new Table({
    client: DocumentClientInstance,
    name: 'MyTable',
    schema: Schema,
    crypto: {
        primary: {
            cipher: 'aes-256-gcm',
            password: '16719023-772f-133d-1111-aaaa7722188f'
        }
    },
}
```

Thanks for pointing this out. We'll update the doc.

**Comment by mobsense** [comment]
Fixed and committed. Thank you.
